[build]
  command = "npm install && ./build"
  publish = "."

[[redirects]]
  from = "/showdown-proxy/*"
  to = "https://sim3.psim.us/:splat"
  status = 200
  force = true

[[redirects]]
  # This is the fix: point the root of your site to the actual client file
  from = "/*"
  to = "/testclient.html"
  status = 200
