[build]
  # This command forces the build and ensures files are in the right spot
  command = "npm install && node build-tools/build-client.js && cp testclient.html index.html"
  publish = "."

[[redirects]]
  from = "/showdown-proxy/*"
  to = "https://sim3.psim.us/:splat"
  status = 200
  force = true
